
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scheduling-system?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
      database: 0
      host: localhost
      port: 6379
#      password: redis(未配置密码，则不写)

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.scheduling.mapper
  configuration:
    map-underscore-to-camel-case: true


